{"fname":"ser216.exception-handling.example","vault":{"fsPath":"vault"},"schemaStub":false,"type":"note","updated":1657678143004,"created":1657678143004,"id":"lN3qf3u1vczxMFQ11oJuC","desc":"","links":[],"anchors":{},"children":["cr4llpre85mb6ylv1m2pc67","ss69fiuh07u07s97j35xt6u","v6kw6lwqfc80oao97j9klcb","scdu0vrtzjm447jvasna8pv","xsur3llb0pnt2v1dteqerzd","d99lec0bbbxscj87idyanli"],"parent":"d8guddw1p0js6ioo2x54avh","data":{},"title":"Example"}
